### ISSUE TITLE
每次调用加密需要先清理public目录并生成一次

### ISSUE THREAD

**Issue by sieveLau** [Li4n0/hugo_encryptor#15]
如果public文件夹有旧的内容，直接hugo生成网站之后调用hugo-encryptor会出现以下错误：
其中***是指我的home目录。
```
Traceback (most recent call last):
  File "hugo-encryptor.py", line 42, in <module>
    md5.update(block['data-password'].encode('utf-8'))
  File "***/.local/lib/python3.8/site-packages/bs4/element.py", line 1016, in __getitem__
    return self.attrs[key]
KeyError: 'data-password'
```
但是先rm -rf了再hugo和加密就不会报错。
或许不是bug，但是可以加到notice里？

**Comment by oyiadin** [comment]
Hi sieve，感谢反馈。Hugo 官方似乎建议[删除 public/ 目录](https://gohugo.io/getting-started/usage/#deploy-your-website)，稍后我会加到 notice 中 ;)

Hi, sieve, thanks for your feedback. It seems that Hugo suggests [remove the public/ directory](https://gohugo.io/getting-started/usage/#deploy-your-website) everytime. I will add a notice later ;)
