### ISSUE TITLE
按照流程执行后网页端无法解密

### ISSUE THREAD

**Issue by NicoleMayer** [Li4n0/hugo_encryptor#2]
![image](https://user-images.githubusercontent.com/32037406/68094692-e3dc8280-fe57-11e9-879a-83b5efe882c3.png)
原来的js代码渲染出来是下面这个样子

![image](https://user-images.githubusercontent.com/32037406/68094647-919b6180-fe57-11e9-8515-1948d643ef61.png)
不知道是不是有什么问题，博客部署后点击按钮没有反应，看console说是找不到 hugoDecrypt 函数？

**Comment by oyiadin** [comment]
Hi，麻烦提供一下 hugo 版本，看起来是 hugo 的 shortcodes 渲染逻辑发生了变动

**Comment by NicoleMayer** [comment]
版本号是 v0.59.0
![image](https://user-images.githubusercontent.com/32037406/68097118-ed6ee600-fe69-11e9-8572-c57b8292404a.png)

**Comment by Li4n0** [comment]
从你博客上渲染好的代码上来看，应该是你的主题把插件插入的 `<script>` 标签里面的代码当做 文本 进行了二次渲染。图里可以看到代码里被插入了行号，并且试图进行代码高亮：
![](https://i.loli.net/2019/11/04/EfBN3ApCS7gnJwb.png)

**Comment by Li4n0** [comment]
@NicoleMayer  很抱歉过了这么久才确认问题并修复...已经明确是因为 Hugo 版本的问题导致的，目前已修复，感谢您的反馈～
