### ISSUE TITLE
显示加密页面，输入密码没反应

### ISSUE THREAD

**Issue by chenui** [Li4n0/hugo_encryptor#9]
在macOS平台上搭建的Hugo，用了hugo_encryptor后，页面显示是加密状态，但是输入密码没反应，不能解密文章。
此外，显示源码，可以显示被加密的内容，这样加密只是显示页面不显示内容，源码还是能看到文章内容。
是哪里弄错了吗

**Comment by oyiadin** [comment]
在使用 `hugo` 命令生成网页文件之后，还需要在相同目录下运行一次 `python hugo-encryptor.py`，您可以检查一下后者的运行情况，或者在这里附上运行后的输出 ;-)

**Comment by chenui** [comment]
好了，加密成功了。问题是：我原来也运行了pyhton hugo-encryptor.py，不过不是在运行hugo的相同目录下，而是在hugo-encryptor.py的所在目录，所以一直不成功。
因为在你写的使用说明中，关于ln hugo-encryptor.py的要求是option，所以开始没有建立这个ln，后来建立这个ln，然后在Hugo网站的根目录运行就正常了，看来建立这个连接应该是必要的步骤。
当时在运行这个hugo-encryptor.py的时候没有信息输出（没有正确信息，也没有错误信息）。希望能升级一下hugo-encryptor的错误提示信息。

**Comment by oyiadin** [comment]
好的👌十分感谢反馈
